# Trigger
on:
  push:


# Defaults of workflow for each run, will use bash shell
defaults:
  run:
    shell: bash

jobs:
  tf_workflow:
    runs-on: ubuntu-latest
    name: "tf Workflow"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: |
        ls -l
        echo $PATH
        env | sort
        aws --version
