# Trigger
on:
  push:


# Defaults of workflow for each run, will use bash shell
defaults:
  run:
    shell: bash

jobs:
  tf_workflow:
    runs-on: ubuntu-latest
    name: "tf Workflow"

    env:
      AWS_ACESS_KEY_ID: ${{ secrets.AWS_ACESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run shell commands
      run: |
        ls -l
        echo $PATH
        env | sort
        aws --version
        $secrets.AWS_ACESS_KEY_ID

    - name: Init
      run: |
        terraform init

    - name: Plan
      run: |
        terraform plan -out tfplan

    - name: Apply
      if: ${{ env.GITHUB_REF_NAME == 'test' }}
      run: |
        terraform apply tfplan
